/* This should be the final file containing relevent information about the artwork (physical and digital),
    and the artist. (objects (phys) + object constituents (links rels b/w art+artist)+ constituents (artist info) + published images (digital))
    
    TODO: Merge la_art_urls with objects
*/

SELECT iiifurl,
iiifthumburl,
accessioned,
title,
displayDate as displayDate_created,
roletype,
`role`,
forwarddisplayname,
birthyear,
deathyear,
ulanid,
artistofngaobject,
nationality,
constituenttype,
demonym,
pct_country_NGA,
artists_countryCode,
artists_continent,
artists_country,
beginyear_artistAssigned,
endyear_artistAssigned,
displaydate_artistAssigned,
country_artistAssigned,
zipcode_artistAssigned,
medium,
dimensions,
inscription,
markings,
attribution,
visualBrowserClassification,
parentID,
isVirtual,
portfolio,
series,
volume,
watermarks,
uuid,
viewtype,
sequence,
width,
height,
maxpixels,
assistivetext,
depictstmsobjectid,
a.objectid,
constituentid
FROM latin_art_urls as a
INNER JOIN objects
ON a.objectid = objects.objectid
