create table constituents (
  constituentID               integer NOT NULL PRIMARY KEY,
  ULANID                      character varying(32) NULL,
  preferredDisplayName        character varying(256) NULL,
  forwardDisplayName          character varying(256) NULL,
  lastName                    character varying(256) NULL,
  displayDate                 character varying(256) NULL,
  artistOfNGAObject           integer NOT NULL,
  beginYear                   integer NULL,
  endYear                     integer NULL,
  visualBrowserTimeSpan       character varying(32) NULL,
  nationality                 character varying(128) NULL,
  visualBrowserNationality    character varying(128) NULL,
  constituentType             character varying(30) NOT NULL
)

CREATE TABLE objects (
    objectID                    integer NOT NULL PRIMARY KEY,
    accessioned                 integer NOT NULL,
    accessionNum                character varying(32) NULL,
    objectLeonardoID            character varying(16) NULL,
    locationID                  integer NULL,
    title                       character varying(2048) NULL,
    displayDate                 character varying(256) NULL,
    beginYear                   integer NULL,
    endYear                     integer NULL,
    visualBrowserTimeSpan       character varying(32) NULL,
    medium                      character varying(2048) NULL,
    dimensions                  character varying(2048) NULL,
    inscription                 character varying NULL,
    markings                    character varying NULL,
    attributionInverted         character varying(1024) NULL,
    attribution                 character varying(1024) NULL,
    creditLine                  character varying(2048) NULL,
    classification              character varying(64) NULL,
    subClassification           character varying(64) NULL,
    visualBrowserClassification character varying(32) NULL,
    provenanceText              character varying(231) NULL,
    parentID                    integer NULL,
    isVirtual                   integer NOT NULL,
    departmentAbbr              character varying(32) NOT NULL,
    portfolio                   character varying(2048) NULL,
    series                      character varying(850) NULL,
    volume                      character varying(850) NULL,
    watermarks                  character varying(512) NULL,
    lastDetectedModification    timestamp with time zone NULL,
    customPrintURL              character varying(2048) NULL
)

